production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: cloud66_development
  pool: 5

test: &test
  adapter: postgresql
  database: cloud66_test

cucumber:
  <<: *test
